In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [131]:
import os
all_dfs = []
directory = os.fsencode("face data/")
for file in os.listdir(directory):
    filename = os.fsdecode(file)
    if filename.endswith("0.csv"): 
        df = pd.read_csv("face data/" + filename, header=None)
        if (filename.endswith("10.csv")):
            df.loc[df[0] == 10, 0] = 1
        all_dfs.append(df)
len(all_dfs)

12

In [132]:
data = pd.concat(all_dfs)
pd.set_option('display.max_rows', 10)
data

,0,1,2,3,4,5,6,7,8,9,...,2491,2492,2493,2494,2495,2496,2497,2498,2499,2500
0,0.0,0.408451,0.265000,0.242236,0.076923,0.061321,0.000000,0.000000,0.531915,0.748299,...,0.235294,0.196078,0.075581,0.011429,0.112426,0.000000,0.000000,0.014286,0.000000,0.000000
1,0.0,0.549505,0.320197,0.227778,0.098592,0.020513,0.000000,0.100000,0.325000,0.432432,...,0.062857,0.021739,0.138122,0.114650,0.092593,0.000000,0.222222,0.000000,0.000000,0.000000
2,0.0,0.158192,0.181395,0.135514,0.082192,0.037838,0.000000,0.248756,0.434146,0.546798,...,0.000000,0.103448,0.155039,0.000000,0.000000,0.000000,0.258065,0.333333,0.266667,0.037037
3,0.0,0.513369,0.213542,0.270968,0.103093,0.072165,0.000000,0.000000,0.306358,0.719424,...,0.167488,0.181818,0.000000,0.073034,0.025974,0.000000,0.000000,0.000000,0.000000,0.419355
4,0.0,0.295597,0.156757,0.133005,0.079208,0.054455,0.000000,0.116751,0.388889,0.557292,...,0.000000,0.013072,0.163934,0.000000,0.000000,0.000000,0.580645,0.205882,0.319149,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,1.0,0.861905,0.836449,0.643836,0.201970,0.333333,0.391061,0.189744,0.457547,0.182692,...,0.015789,0.036649,0.139175,0.078125,0.135678,0.138095,0.185000,0.641414,0.805263,0.766355
11,1.0,0.769737,0.853982,0.847619,0.852018,0.848485,0.879310,0.884956,0.994924,0.935961,...,0.043011,0.029412,0.064516,0.142105,0.128713,0.105727,0.095455,0.088608,0.029915,0.004405
12,1.0,0.846890,0.843750,0.836283,0.871560,0.640449,0.324324,0.190244,0.328638,0.470874,...,0.034483,0.072072,0.137405,0.093750,0.079787,0.070423,0.000000,0.004367,0.000000,0.000000
13,1.0,0.851852,0.856481,0.873874,0.868778,0.896396,1.000000,0.675393,0.287805,0.325123,...,0.104651,0.070922,0.105634,0.049505,0.075117,0.063063,0.000000,0.000000,0.000000,0.000000
14,1.0,0.841860,0.852679,0.876712,1.000000,0.320000,0.206522,0.324873,0.460396,0.240000,...,0.081395,0.078261,0.026846,0.088757,0.093567,0.066667,0.063636,0.000000,0.000000,0.000000

In [133]:
X = data.iloc[:, [i for i in range(1, 2501)]]
Y = data.iloc[:, 0]
X

,1,2,3,4,5,6,7,8,9,10,...,2491,2492,2493,2494,2495,2496,2497,2498,2499,2500
0,0.408451,0.265000,0.242236,0.076923,0.061321,0.000000,0.000000,0.531915,0.748299,0.835821,...,0.235294,0.196078,0.075581,0.011429,0.112426,0.000000,0.000000,0.014286,0.000000,0.000000
1,0.549505,0.320197,0.227778,0.098592,0.020513,0.000000,0.100000,0.325000,0.432432,0.568750,...,0.062857,0.021739,0.138122,0.114650,0.092593,0.000000,0.222222,0.000000,0.000000,0.000000
2,0.158192,0.181395,0.135514,0.082192,0.037838,0.000000,0.248756,0.434146,0.546798,0.805755,...,0.000000,0.103448,0.155039,0.000000,0.000000,0.000000,0.258065,0.333333,0.266667,0.037037
3,0.513369,0.213542,0.270968,0.103093,0.072165,0.000000,0.000000,0.306358,0.719424,0.808824,...,0.167488,0.181818,0.000000,0.073034,0.025974,0.000000,0.000000,0.000000,0.000000,0.419355
4,0.295597,0.156757,0.133005,0.079208,0.054455,0.000000,0.116751,0.388889,0.557292,0.770370,...,0.000000,0.013072,0.163934,0.000000,0.000000,0.000000,0.580645,0.205882,0.319149,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,0.861905,0.836449,0.643836,0.201970,0.333333,0.391061,0.189744,0.457547,0.182692,0.171569,...,0.015789,0.036649,0.139175,0.078125,0.135678,0.138095,0.185000,0.641414,0.805263,0.766355
11,0.769737,0.853982,0.847619,0.852018,0.848485,0.879310,0.884956,0.994924,0.935961,0.912195,...,0.043011,0.029412,0.064516,0.142105,0.128713,0.105727,0.095455,0.088608,0.029915,0.004405
12,0.846890,0.843750,0.836283,0.871560,0.640449,0.324324,0.190244,0.328638,0.470874,0.311881,...,0.034483,0.072072,0.137405,0.093750,0.079787,0.070423,0.000000,0.004367,0.000000,0.000000
13,0.851852,0.856481,0.873874,0.868778,0.896396,1.000000,0.675393,0.287805,0.325123,0.371429,...,0.104651,0.070922,0.105634,0.049505,0.075117,0.063063,0.000000,0.000000,0.000000,0.000000
14,0.841860,0.852679,0.876712,1.000000,0.320000,0.206522,0.324873,0.460396,0.240000,0.207729,...,0.081395,0.078261,0.026846,0.088757,0.093567,0.066667,0.063636,0.000000,0.000000,0.000000

In [134]:
X_Data = []
for _, row in X.iterrows():
    X_Data.append(np.array(row).reshape(50, 50))

In [165]:
from sklearn.model_selection import train_test_split
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X_Data, Y, test_size = 0.20, shuffle=True)

In [166]:
X_Train = np.array(X_Train).reshape(len(X_Train), 50, 50, 1)
X_Test = np.array(X_Test).reshape(len(X_Test), 50, 50, 1)
Y_Train = np.array(Y_Train)
Y_Tests = np.array(Y_Test)
X_Train.shape

(185, 50, 50, 1)

In [167]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(64, (3,3), activation='relu', input_shape=(50, 50, 1)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2,2),
  tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
  tf.keras.layers.MaxPooling2D(2,2),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(1024, activation='relu'),
  tf.keras.layers.Dense(2, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_25"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv2d_58 (Conv2D)           (None, 48, 48, 64)        640
_________________________________________________________________
max_pooling2d_58 (MaxPooling (None, 24, 24, 64)        0
_________________________________________________________________
conv2d_59 (Conv2D)           (None, 22, 22, 64)        36928
_________________________________________________________________
max_pooling2d_59 (MaxPooling (None, 11, 11, 64)        0
_________________________________________________________________
conv2d_60 (Conv2D)           (None, 9, 9, 64)          36928
_________________________________________________________________
max_pooling2d_60 (MaxPooling (None, 4, 4, 64)          0
_________________________________________________________________
flatten_27 (Flatten)         (None, 1024)              0
_________________________________________________________________
dense_50 (Dense)             (None, 1024)              1049600
_________________________________________________________________
dense_51 (Dense)             (None, 2)                 2050
=================================================================
Total params: 1,126,146
Trainable params: 1,126,146
Non-trainable params: 0
_________________________________________________________________

In [172]:
model.fit(X_Train, Y_Train, epochs=10)

Epoch 1/10
6/6 [==============================] - 1s 105ms/step - loss: 0.0501 - accuracy: 0.9946
Epoch 2/10
6/6 [==============================] - 1s 112ms/step - loss: 0.0244 - accuracy: 1.0000
Epoch 3/10
6/6 [==============================] - 1s 112ms/step - loss: 0.0101 - accuracy: 1.0000
Epoch 4/10
6/6 [==============================] - 1s 110ms/step - loss: 0.0049 - accuracy: 1.0000
Epoch 5/10
6/6 [==============================] - 1s 114ms/step - loss: 0.0022 - accuracy: 1.0000
Epoch 6/10
6/6 [==============================] - 1s 115ms/step - loss: 5.8855e-04 - accuracy: 1.0000
Epoch 7/10
6/6 [==============================] - 1s 109ms/step - loss: 6.5032e-04 - accuracy: 1.0000
Epoch 8/10
6/6 [==============================] - 1s 108ms/step - loss: 3.3990e-04 - accuracy: 1.0000
Epoch 9/10
6/6 [==============================] - 1s 111ms/step - loss: 3.6535e-04 - accuracy: 1.0000
Epoch 10/10
6/6 [==============================] - 1s 110ms/step - loss: 2.7083e-04 - accuracy: 1.0000

In [173]:
model.evaluate(X_Test, Y_Test)

2/2 [==============================] - 0s 20ms/step - loss: 0.0985 - accuracy: 0.9787

[0.09851307421922684, 0.978723406791687]

In [174]:
Y_Pred = np.argmax(model.predict(X_Test), axis=-1)
Y_Pred

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0], dtype=int64)

In [175]:
con_mat = tf.math.confusion_matrix(labels=Y_Test, predictions=Y_Pred).numpy()
con_mat_norm = np.around(con_mat.astype('float') / con_mat.sum(axis=1)[:, np.newaxis], decimals=2)
con_mat_norm

array([[0.96, 0.04],
       [0.  , 1.  ]])